### ISSUE TITLE
Default behavior for printer/pdf should be to expand register details

### ISSUE THREAD

**Issue by rolsen** [labjack/ljsimpleregisterlookup#8]
The method we used for https://labjack.com/support/datasheets/t-series/communication/stream-mode/stream-out/stream-out-description was the following script, which checks for the shopping cart's existence:

```
<script>
// Register a "on document ready" function callback.
jQuery(document).ready(function() {
// Search page for the shopping cart icon.
var cartIcon = jQuery('.region-header-top #block-system-user-menu .leaf.cart');

try {
// See if the shopping cart icon exists
if(cartIcon.length >= 1) {
// if it exists then we are not a printer.
} else {
// if it doesn't exist then we are a printer.
jQuery('#stream-out-presentation').hide()
jQuery('#stream-out-presentation-print-warning').show()
}
} catch(err) {
// we must be a printer
jQuery('#stream-out-presentation').hide()
jQuery('#stream-out-presentation-print-warning').show()
}
});

</script>
```

**Comment by rolsen** [comment]
That autoscribe view is deployed, right?

1. I'm seeing that with the Save as PDF button, it adds a '&print=true' below each ljsimpleregisterlookup segment, but doesn't expand them.

2. With the Chrome > File > Print, the print preview shows unexpanded ljsimpleregisterlookup segements.

Chrome 69.0.3497.100, if that matters.

**Comment by CalebNeelCO** [comment]
merging the pull request will fix this

**Comment by rolsen** [comment]
#11, for reference
